name: Export Power Platform Solution

on:
  workflow_dispatch:

env:
  SolutionName: ${{ vars.SolutionName }}
  PP_Environment: ${{ vars.DevEnvironment }}

permissions:
  contents: write

jobs:
  Power-Platform-Export:
    runs-on: ubuntu-latest

    steps:

      # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
        environment-url: ${{ env.PP_Environment }}
        app-id: ${{ secrets.POWERPLATFORM_APP_ID }}
        client-secret: ${{ secrets.POWERPLATFORM_CLIENT_SECRET }}
        tenant-id: ${{ secrets.POWERPLATFORM_TENANT_ID }}

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' 
    
    - name: Install Power Platform CLI
      run: npm install -g @microsoft/powerplatform-cli
      
    - name: Export Solution
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: '${{ env.PP_Environment }}'
        app-id: ${{ secrets.POWERPLATFORM_APP_ID }}
        client-secret: ${{ secrets.POWERPLATFORM_CLIENT_SECRET }}
        tenant-id: ${{ secrets.POWERPLATFORM_TENANT_ID }}
        solution-name: ${{ env.SolutionName }}
        solution-output-file: '${{ env.SolutionName }}.zip'
        working-directory: 'PowerPlatform/AliceforAccounts'
        managed: true
        overwrite: true

    - name: Unpack Solution
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: 'PowerPlatform/AliceforAccounts/${{ env.SolutionName }}'
        solution-folder: '/PowerPlatform/AliceforAccounts'
        solution-type: 'Managed'
        overwrite-files: true

    - name: Prepare solution changes for check-in into source control
      uses: microsoft/powerplatform-actions/branch-solution@v1
      with:
        solution-folder: '/PowerPlatform/AliceforAccounts'
        solution-target-folder: '/PowerPlatform/AliceforAccounts'
        token: ${{ secrets.GITHUB_TOKEN }}