name: Power Platform CI/CD Pipeline

on:
  workflow_dispatch:

env:
  SolutionName: ${{ vars.SolutionName }}

jobs:
  Power-Platform-Deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Install Power Platform CLI tools
    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    # Pack Power Platform Solution
    - name: Power Platform Pack Solution
      uses: microsoft/powerplatform-actions/pack-solution@v1
      with:
        solution-folder: ${{ github.workspace }}/PowerPlatform/AliceforAccounts
        solution-file: ${{ github.workspace }}/PowerPlatform/${{ env.SolutionName }}_Managed.zip
        solution-type: Managed

    # Import Power Platform Solution
    - name: Power Platform Import Solution
      uses: microsoft/powerplatform-actions/import-solution@v1
      with:
        solution-file: ${{ github.workspace }}/PowerPlatform/${{ env.SolutionName }}_Managed.zip
        run-asynchronously: true
        force-overwrite: true
        publish-changes: true
        environment-url: ${{ secrets.POWERPLATFORM_ENV_URL }}
        app-id: ${{ secrets.POWERPLATFORM_APP_ID }}
        client-secret: ${{ secrets.POWERPLATFORM_CLIENT_SECRET }}
        tenant-id: ${{ secrets.POWERPLATFORM_TENANT_ID }}

  Logic-App-Deploy:
   runs-on: ubuntu-latest
   steps:
    # Update Values in ARM Template using PowerShell
    - name: Update Values in ARM Template
      uses: azure/powershell@v1
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ./CICD/replace_dataset.ps1 -source_path "${{ github.workspace }}/LogicApps" -input_dataset "${{ github.workspace }}/data_set_TEST.json"

    # Deploy ARM Template
    - name: ARM Template Deployment
      uses: azure/arm-deploy@v1
      with:
        deploymentScope: resourceGroup
        resourceGroupName: rg-ne-alice-test
        location: North Europe
        template: ${{ github.workspace }}/LogicApps/template.json
        parameters: ${{ github.workspace }}/LogicApps/parameters.json
        azureResourceManagerConnection: ${{ secrets.AZURE_RM_CONNECTION }}
